extends: airbnb-base
overrides:
  files:
    - src/**/*.ts
    - index.ts
  parser: typescript-eslint-parser
  rules:
    no-undef: off
    no-unused-vars: off
    no-param-reassign: off
    import/extensions: off
    import/no-unresolved: off
    no-underscore-dangle: off
    class-methods-use-this: off
    no-return-assign: off
    import/prefer-default-export: off
    no-restricted-globals: off
    consistent-return: off;
    semi: off;
