language: node_js
node_js:
- '9'
- '8'
- '7'
- '6'
cache:
  directories:
  - node_modules
notifications:
  email: false
install:
- npm install
script:
- npm run build
- npm run test
after_script:
- cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
after_success:
  - npm run docs
  - npm run build
  - npm run travis-deploy-once "npm run semantic-release"
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_DEPLOY_TOKEN
  local-dir: docs
  on:
    branch: master
