language: node_js
node_js:
- '12'
- '10'
cache:
  directories:
  - node_modules
notifications:
  email: false
install:
- yarn
script:
- yarn build
- yarn test
after_script:
- cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
branches:
  only:
    - master
jobs:
  include:
    - stage: deploy
      script: yarn docs
      deploy:
        provider: pages
        cleanup: false
        github-token: $GH_TOKEN
        local-dir: docs
        on:
          branch: master
    - script:
      - yarn build
      - yarn semantic-release
